### ISSUE TITLE
feat: Support Declare transactions

### ISSUE THREAD

**Issue by ftheirs** [keep-starknet-strange/snos#354]
**Describe the Feature Request**
Snos panics on blocks with Declare transactions. In order to achieve this, several parts of the code need to handle/implement what is required to process these transactions

Branch WIP: https://github.com/keep-starknet-strange/snos/tree/ft/declare_txs

**Related Code**

**Additional Context**
On the comments, the different issues that will be described and link the PR/commit from the fix

**Comment by ftheirs** [comment]
Tested on block `79984`
Console output:
```
[DEBUG minilp::solver] restored feasibility in 268 iterations, obj.: 10781510
thread 'main' panicked at crates/bin/prove_block/src/main.rs:36:61:
Block could not be proven: RpcError(StarknetError(ContractNotFound))
```

Fix: https://github.com/keep-starknet-strange/snos/pull/352

**Comment by ftheirs** [comment]
Tested on block: `76840`

Console output:
```
[DEBUG blockifier::transaction::transactions] Transaction execution failed with: Failed to read from state: ClassHashNotFound.
thread 'main' panicked at /Users/ftheirs/Repositories/snos/crates/bin/prove_block/src/reexecute.rs:57:21:
Transaction 736032479bace4146d6551c0570299d5a7701218024dd6cedd6a1e0836a0659 (11/14) failed in blockifier: Failed to read from state: ClassHashNotFound.
stack backtrace:
```
Context: This error was triggered when reexecuting the previous block (block_number - 1). After debugging, the error is detected in Blockifier but it was actually calling`get_compiled_contract_class_async` function from `rpc_state_reader`. Since the ContractClass is not defined in the previous block, the RPC throws an error. The fix consist in remapping this error.
Fix: https://github.com/keep-starknet-strange/snos/commit/8dce2be3527bb0ba7f5203c2c1177357556d313d

**Comment by ftheirs** [comment]
Tested on block: `76840` and `160966`

Console output:
`assertion failed: previous_class_proof.verify(*class_hash).is_ok()
`

Context:
[These asserts](https://github.com/keep-starknet-strange/snos/blob/2548445dfb91e91dd2c3cf03351da5f4361053fb/crates/bin/prove_block/src/lib.rs#L70-L76) were failing. After careful inspection, there were some bugs that had to be fixed.

```
for (class_hash, previous_class_proof) in previous_class_proofs {
    assert!(previous_class_proof.verify(*class_hash).is_ok());
}

for (class_hash, class_proof) in previous_class_proofs {
    assert!(class_proof.verify(*class_hash).is_ok());
}
```

Fix: https://github.com/keep-starknet-strange/snos/commit/e885d2476663f47efcc37ad6e58e40968530dbc4

PS: the fix solved the issue for block `76840`. The other block keeps failing on the assert from previous class proofs

**Comment by ftheirs** [comment]
Tested on block: `76840`

Console output:
```
[ERROR prove_block] died at: /Users/ftheirs/Repositories/snos/cairo-lang/src/starkware/cairo/common/dict.cairo:56
[ERROR prove_block] inst_location:
    Location { end_line: 66, end_col: 7, input_file: InputFile { filename: "/Users/ftheirs/Repositories/snos/cairo-lang/src/starkware/cairo/common/dict.cairo" }, parent_location: None, start_line: 56, start_col: 5 }
thread 'main' panicked at crates/bin/prove_block/src/main.rs:36:61:
Block could not be proven: SnOsError(Runner(VmException(VmException { pc: Relocatable { segment_index: 0, offset: 252 }, inst_location: Some(Location { end_line: 66, end_col: 7, input_file: InputFile { filename: "/Users/ftheirs/Repositories/snos/cairo-lang/src/starkware/cairo/common/dict.cairo" }, parent_location: None, start_line: 56, start_col: 5 }), inner_exc: Hint((0, WrongPrevValue((Int(0), Int(1081521228881763032381340369983304581869719834203569457582430923958602864337), Int(2790843345387106728836781645678935291925327034839673762138726424037927125171))))), error_attr_value: None, traceback: Some("Cairo traceback (most recent call last):\ncairo-lang/src/starkware/starknet/core/os/os.cairo:94:49: (pc=0:11641)\n        let (local reserved_range_checks_end) = execute_transactions(block_context=block_context);\n                                                ^***********************************************^\n/Users/ftheirs/Repositories/snos/cairo-lang/src/starkware/starknet/core/os/execution/execute_transactions.cairo:168:5: (pc=0:10392)\n            'execution_helper': execution_helper,\n    ^*******************************************^\n/Users/ftheirs/Repositories/snos/cairo-lang/src/starkware/starknet/core/os/execution/execute_transactions.cairo:267:20: (pc=0:10463)\n    let remaining_gas = INITIAL_GAS_COST - TRANSACTION_GAS_COST;\n                   ^**********************************************************************^\n/Users/ftheirs/Repositories/snos/cairo-lang/src/starkware/starknet/core/os/execution/execute_transactions.cairo:267:20: (pc=0:10463)\n    let remaining_gas = INITIAL_GAS_COST - TRANSACTION_GAS_COST;\n                   ^**********************************************************************^\n/Users/ftheirs/Repositories/snos/cairo-lang/src/starkware/starknet/core/os/execution/execute_transactions.cairo:284:9: (pc=0:10526)\n            %{ exit_tx() %}\n        ^******************************************************^\n/Users/ftheirs/Repositories/snos/cairo-lang/src/starkware/starknet/core/os/execution/execute_transactions.cairo:1063:9: (pc=0:11424)\n    }\n        ^\n") })))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Context:
The issue comes from 
`WrongPrevValue((Int(0), Int(2914380022048590530662957512768899582721003481667668281362650132041708924227), Int(376777264310724238292765590161100262470936922835543311980000322853526649051))))) in cairo-lang/src/starkware/starknet/core/os/execution/execute_transactions.cairo:1063:`

And that's when updating a Cairo dictionary called contract_class_changes which is built from the class_hash_to_compiled_class_hash dict in the OS input. The comment above explicits that the value should be 0 for new classes:
```
// Note that prev_value=0 enforces that a class may be declared only once.
dict_update{dict_ptr=contract_class_changes}(
    key=[class_hash_ptr], prev_value=0, new_value=compiled_class_hash
);
```

Fix: https://github.com/keep-starknet-strange/snos/commit/86bd535292b5e2d7c4768e584c1032e6ebeddc16
